

server:
  port: 8090 


spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=MovieDb
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ozaytunctan
    password: tunctan13
  jpa:
    database: sql-server
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
     

     
     
movie:
 prop:
   api-key: 563ad9aa
   omdb-id: tt3896198
   omdb-base-url: http://www.omdbapi.com/?i=tt3896198&apikey=563ad9aa&s=%s
    
#debug: true
 
    
